"""LAMMPS execution + output parsing (Phase 4 / Session 4.2).

Runs ``lmp`` on inputs generated by
:mod:`backend.common.engines.lammps_input` (Session 4.1) and parses
the resulting ``log.lammps`` + trajectory dump files into structured
Python.

Mirrors the :mod:`backend.common.engines.qe_run` shape: a
sync-callable ``run_lammps`` plus standalone parsers for log + dump.
Execution goes through the Session 2.3 execution backend so cancel +
walltime work the same way as for QE.

Public API
----------

- :func:`run_lammps` — submit + poll + parse, returns :class:`LAMMPSRunResult`.
- :func:`parse_lammps_log` — :class:`LAMMPSLog` from ``log.lammps``.
- :func:`parse_lammps_dump` — iterator over :class:`TrajectoryFrame`.
- :func:`compute_rdf`, :func:`compute_msd` — analyzers (MVP subset;
  VACF / Green-Kubo land in a follow-up when there's real need).
"""

from .analyzers import MSDResult, RDFResult, compute_msd, compute_rdf
from .log import LAMMPSLog, LAMMPSLogParseError, ThermoTable, parse_lammps_log
from .runner import LAMMPSRunError, LAMMPSRunResult, run_lammps
from .trajectory import (
    TrajectoryFrame,
    TrajectoryParseError,
    parse_lammps_dump,
)

__all__ = [
    "LAMMPSLog",
    "LAMMPSLogParseError",
    "LAMMPSRunError",
    "LAMMPSRunResult",
    "MSDResult",
    "RDFResult",
    "ThermoTable",
    "TrajectoryFrame",
    "TrajectoryParseError",
    "compute_msd",
    "compute_rdf",
    "parse_lammps_dump",
    "parse_lammps_log",
    "run_lammps",
]
