# ORION Platform Configuration
# ============================

app:
  name: "ORION"
  version: "1.0.0"
  tagline: "Charting new frontiers in material science"
  environment: "development"  # development, staging, production

# Database Configuration
database:
  postgres:
    host: "${POSTGRES_HOST:localhost}"
    port: 5432
    database: "orion_db"
    user: "${POSTGRES_USER:orion}"
    password: "${POSTGRES_PASSWORD:orion_secure_pwd}"
    pool_size: 20
    max_overflow: 40
  
  neo4j:
    uri: "${NEO4J_URI:bolt://localhost:7687}"
    user: "${NEO4J_USER:neo4j}"
    password: "${NEO4J_PASSWORD:neo4j_secure_pwd}"
    encrypted: false
    trust: "TRUST_ALL_CERTIFICATES"
  
  redis:
    host: "${REDIS_HOST:localhost}"
    port: 6379
    db: 0
    password: "${REDIS_PASSWORD:}"
    decode_responses: true
    socket_timeout: 5
    connection_pool_kwargs:
      max_connections: 50
  
  mongodb:
    uri: "${MONGODB_URI:mongodb://localhost:27017}"
    database: "orion_documents"
    collection: "materials"

# Knowledge Graph Configuration
knowledge_graph:
  ontology:
    namespaces:
      mat: "http://orion.ai/ontology/material#"
      proc: "http://orion.ai/ontology/process#"
      prop: "http://orion.ai/ontology/property#"
      meth: "http://orion.ai/ontology/method#"
      unit: "http://orion.ai/ontology/unit#"
  
  schema:
    version: "1.0.0"
    auto_index: true
    constraints:
      - "CREATE CONSTRAINT material_formula IF NOT EXISTS ON (m:Material) ASSERT m.formula IS UNIQUE"
      - "CREATE CONSTRAINT process_id IF NOT EXISTS ON (p:Process) ASSERT p.id IS UNIQUE"
  
  etl:
    batch_size: 1000
    parallel_workers: 4
    checkpoint_interval: 5000

# RAG Configuration
rag:
  embedding:
    model: "sentence-transformers/all-mpnet-base-v2"
    dimension: 768
    batch_size: 32
    normalize: true
  
  retrieval:
    sparse_weight: 0.4
    dense_weight: 0.6
    top_k: 8
    rerank_top_n: 12
    score_threshold: 0.2
    chunk_size: 512
    chunk_overlap: 20
  
  faiss:
    index_type: "HNSWFlat"  # HNSWFlat, IVF_PQ
    hnsw_m: 32
    ef_construction: 200
    ef_search: 64
  
  elasticsearch:
    index_name: "orion_materials"
    shards: 3
    replicas: 1
  
  cache:
    ttl: 21600  # 6 hours
    max_size: 10000

# LLM Configuration
llm:
  provider: "openai"  # openai, anthropic, local
  model: "gpt-4-turbo-preview"
  temperature: 0.7
  max_tokens: 4096
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0
  
  fallback_models:
    - "gpt-3.5-turbo-16k"
    - "claude-2.1"
  
  local:
    model_path: "/models/llama-2-70b"
    device: "cuda"
    load_in_8bit: true

# Simulation Configuration
simulation:
  engines:
    vasp:
      executable: "/opt/vasp/bin/vasp_std"
      potcar_path: "/opt/vasp/potcars"
      default_params:
        encut: 520
        ediff: 1e-6
        ismear: 0
        sigma: 0.05
    
    quantum_espresso:
      executable: "/opt/qe/bin/pw.x"
      pseudo_path: "/opt/qe/pseudo"
      default_params:
        ecutwfc: 50
        conv_thr: 1e-8
    
    lammps:
      executable: "/opt/lammps/bin/lmp"
      potential_path: "/opt/lammps/potentials"
  
  queue:
    scheduler: "slurm"  # slurm, pbs, local
    partition: "gpu"
    nodes: 1
    ntasks: 16
    time_limit: "24:00:00"
    memory: "64GB"
  
  orchestration:
    max_concurrent_jobs: 10
    retry_attempts: 3
    retry_delay: 300
    checkpoint_interval: 3600

# Experimental Design
experimental:
  protocol_templates: "/workspace/orion-platform/templates/protocols"
  safety_database: "/workspace/orion-platform/data/safety"
  equipment_registry: "/workspace/orion-platform/config/equipment.yaml"
  
  synthesis_methods:
    - "sol_gel"
    - "cvd"
    - "ald"
    - "hydrothermal"
    - "solid_state"
    - "electrochemical"
  
  characterization_techniques:
    - "xrd"
    - "sem"
    - "tem"
    - "xps"
    - "raman"
    - "ftir"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  cors:
    origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]
  
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
  
  authentication:
    secret_key: "${JWT_SECRET_KEY:your-secret-key-here}"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7

# UI Configuration
ui:
  streamlit:
    port: 8501
    theme: "dark"
    wide_mode: true
  
  gradio:
    port: 7860
    share: false
    auth: false

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15
  
  grafana:
    enabled: true
    port: 3000
    admin_user: "admin"
    admin_password: "${GRAFANA_PASSWORD:admin}"
  
  logging:
    level: "INFO"
    format: "json"
    file: "/var/log/orion/orion.log"
    max_size: "100MB"
    backup_count: 10
  
  alerts:
    email:
      enabled: true
      smtp_host: "smtp.gmail.com"
      smtp_port: 587
      from_address: "orion-alerts@example.com"
      to_addresses: ["admin@example.com"]
    
    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL:}"

# Storage Configuration
storage:
  type: "s3"  # s3, gcs, azure, local
  
  s3:
    bucket: "orion-materials"
    region: "us-east-1"
    access_key: "${AWS_ACCESS_KEY_ID:}"
    secret_key: "${AWS_SECRET_ACCESS_KEY:}"
  
  local:
    base_path: "/workspace/orion-platform/data"
    
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30

# Machine Learning Configuration
ml:
  training:
    batch_size: 32
    epochs: 100
    learning_rate: 0.001
    early_stopping_patience: 10
    validation_split: 0.2
  
  models:
    save_path: "/workspace/orion-platform/models"
    checkpoint_interval: 5
    best_model_metric: "val_loss"
  
  experiment_tracking:
    mlflow:
      tracking_uri: "http://localhost:5000"
      experiment_name: "orion_materials"
    
    wandb:
      project: "orion-materials"
      entity: "orion-team"

# Security Configuration
security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  
  ssl:
    enabled: true
    cert_file: "/etc/ssl/certs/orion.crt"
    key_file: "/etc/ssl/private/orion.key"
  
  api_keys:
    materials_project: "${MP_API_KEY:}"
    pubchem: "${PUBCHEM_API_KEY:}"
    chembl: "${CHEMBL_API_KEY:}"

# Feature Flags
features:
  active_learning: true
  ensemble_predictions: true
  uncertainty_quantification: true
  automated_experiments: true
  real_time_monitoring: true
  collaborative_filtering: false

# Performance Tuning
performance:
  cache:
    query_cache_size: "1GB"
    result_cache_ttl: 3600
  
  threading:
    max_workers: 16
    queue_size: 1000
  
  gpu:
    device_ids: [0, 1]
    memory_fraction: 0.8
    allow_growth: true