"""QE execution + output parsing (Phase 3 / Session 3.2).

Runs ``pw.x`` on inputs generated by :mod:`backend.common.engines.qe_input`
(Session 3.1) and parses the resulting output file into a structured
:class:`PWOutput` object.

Design boundary
---------------

- No imports of Celery or SQLAlchemy. The Celery task in
  ``src.worker.tasks`` glues this package to the job state machine.
- Execution goes through the execution backend abstraction from
  Session 2.3 (``LocalBackend`` or ``SlurmBackend``) — we never call
  ``subprocess`` directly here.
"""

from .output import (
    ConvergenceStatus,
    ParsedEnergy,
    ParsedForce,
    ParsedStress,
    PWOutput,
    PWOutputParseError,
    parse_pw_output,
)
from .runner import PWRunError, PWRunResult, run_pw

__all__ = [
    "ConvergenceStatus",
    "ParsedEnergy",
    "ParsedForce",
    "ParsedStress",
    "PWOutput",
    "PWOutputParseError",
    "PWRunError",
    "PWRunResult",
    "parse_pw_output",
    "run_pw",
]
