apiVersion: v1
kind: Namespace
metadata:
  name: orion-platform
  labels:
    app: orion
    environment: base
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: orion-quota
  namespace: orion-platform
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "20"
    services: "20"
    pods: "100"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: orion-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-orion-internal
  namespace: orion-platform
spec:
  podSelector:
    matchLabels:
      app: orion
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: orion-platform
    - podSelector:
        matchLabels:
          app: orion
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: orion-platform
    - podSelector:
        matchLabels:
          app: orion
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80